name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create Kind Cluster
      run: kind create cluster --name kind

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        kind get kubeconfig --name kind > $HOME/.kube/config

    - name: Print Kubeconfig
      run: cat $HOME/.kube/config

    - name: Test Kubernetes Connection
      run: kubectl cluster-info

    - name: Get Nodes
      run: kubectl get nodes

    - name: Describe Nodes
      run: kubectl describe nodes

    - name: Get All Pods
      run: kubectl get pods --all-namespaces
